allowBuilds:
  esbuild: false
  msw: false

blockExoticSubdeps: true

catalog:
  #  '@chromatic-com/storybook': 5.3.0
  '@storybook/addon-a11y': 10.5.10
  '@storybook/addon-docs': 10.5.10
  '@storybook/addon-onboarding': 10.5.10
  #  '@storybook/addon-themes': 10.5.10
  #  '@storybook/addon-vitest': 10.5.10
  '@storybook/react-vite': 10.5.10
  '@fontsource-variable/inter': 5.3.0
  '@internationalized/date': 3.12.3
  '@js-temporal/polyfill': 0.5.1
  #  '@stylexjs/stylex': 0.19.0
  #  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': 4.3.3
  '@tanstack/eslint-plugin-query': 5.101.4
  '@tanstack/eslint-plugin-router': 1.162.0
  '@tanstack/react-form': 2.0.0-alpha.1
  '@tanstack/react-pacer': 0.23.0
  '@tanstack/react-store': 0.11.1
  '@tanstack/react-table': 9.1.2
  '@tanstack/react-virtual': 3.14.9
  '@tanstack/store': 0.11.1
  '@thaz/form-util': 1.0.0-rc.5
  '@thaz/oxfmt-config': 1.0.0-rc.3
  '@thaz/oxlint-config': 1.0.0-rc.2
  '@thaz/temporal-util': 1.0.0-rc.3
  '@thaz/typescript-config': 1.0.0-rc.2
  '@total-typescript/ts-reset': 0.6.1
  '@ts-rest/core': 3.53.0-rc.1
  '@types/node': 24.13.3
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  '@vitejs/plugin-react': 6.0.5
  #  '@vitest/coverage-istanbul': 4.1.10
  #  '@vitest/browser-playwright': 4.1.10
  #  '@vitest/ui': 4.1.10
  eslint-plugin-react-hooks-extra: 2.13.0
  eslint-plugin-react-naming-convention: 2.13.0
  eslint-plugin-react-web-api: 2.13.0
  lucide-react: 1.33.0
  #  playwright: 1.62.1
  react: 19.2.8
  #  react-aria: 3.47.0
  react-aria-components: 1.20.0
  react-dom: 19.2.8
  storybook: 10.5.10
  tailwind-merge: 3.6.0
  tailwind-variants: 3.3.1
  tailwindcss: 4.3.3
  temporal-polyfill: 1.0.4
  type-fest: 5.8.0
  typescript: 6.0.3
  valibot: 1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plugin-externalize-deps: 0.10.0
  vite-plus: 0.2.9
#  vitest: 4.1.10

catalogMode: prefer
# Watch this issue: https://github.com/pnpm/pnpm/issues/11238
minimumReleaseAge: 4320 # 3 days just to be safe with the uptick of supply chain attacks

minimumReleaseAgeExclude:
  - '@thaz/form-util@1.0.0-rc.5'
  - '@thaz/network-util@1.0.0-rc.1'
  - '@thaz/oxfmt-config@1.0.0-rc.3'
  - '@thaz/oxlint-config@1.0.0-rc.2'
  - '@thaz/temporal-util@1.0.0-rc.3'
  - '@thaz/typescript-config@1.0.0-rc.2'
  - '@voidzero-dev/vite-plus-core@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.9'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.9'
  - vite-plus@0.2.9

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
