import {
  aggregationFn_sum,
  aggregationFn_min,
  aggregationFn_max,
  aggregationFn_extent,
  aggregationFn_mean,
  aggregationFn_median,
  aggregationFn_unique,
  aggregationFn_uniqueCount,
  aggregationFn_first,
  aggregationFn_last,
  createFilteredRowModel,
  createSortedRowModel,
  createExpandedRowModel,
  createColumnHelper,
  filterFn_arrIncludes,
  filterFn_arrIncludesAll,
  filterFn_arrHas,
  filterFn_arrIncludesSome,
  filterFn_between,
  filterFn_betweenInclusive,
  filterFn_empty,
  filterFn_endsWith,
  filterFn_equals,
  filterFn_equalsString,
  filterFn_equalsStringSensitive,
  filterFn_inDateRange,
  filterFn_inNumberRange,
  filterFn_includesString,
  filterFn_includesStringSensitive,
  filterFn_notEmpty,
  filterFn_startsWith,
  filterFn_weakEquals,
  metaHelper,
  cellSelectionFeature,
  cellSpanningFeature,
  columnFacetingFeature,
  columnFilteringFeature,
  columnGroupingFeature,
  columnOrderingFeature,
  columnPinningFeature,
  columnResizingFeature,
  columnSizingFeature,
  columnVisibilityFeature,
  globalFilteringFeature,
  rowAggregationFeature,
  rowExpandingFeature,
  rowPaginationFeature,
  rowPinningFeature,
  rowSelectionFeature,
  rowSortingFeature,
  sortFn_alphanumeric,
  sortFn_alphanumericCaseSensitive,
  sortFn_basic,
  sortFn_datetime,
  sortFn_text,
  sortFn_textCaseSensitive,
  tableFeatures,
} from '@tanstack/react-table';
import type { RowData } from '@tanstack/react-table';

import type { DataTableColumnMeta } from '#src/common/components/data-table/lib/filter-fns';
import {
  aggregation_zoned_date_time_min,
  aggregation_zoned_date_time_max,
  aggregation_zoned_date_time_extent,
  aggregation_instant_min,
  aggregation_instant_max,
  aggregation_instant_extent,
  aggregation_plain_date_time_min,
  aggregation_plain_date_time_max,
  aggregation_plain_date_time_extent,
  aggregation_plain_date_min,
  aggregation_plain_date_max,
  aggregation_plain_date_extent,
  aggregation_plain_time_min,
  aggregation_plain_time_max,
  aggregation_plain_time_extent,
} from '#src/common/components/data-table/lib/aggregate-fns';
import {
  filter_zoned_date_time_equals,
  filter_zoned_date_time_not_equal,
  filter_zoned_date_time_greater_than,
  filter_zoned_date_time_greater_than_or_equal,
  filter_zoned_date_time_less_than,
  filter_zoned_date_time_less_than_or_equal,
  filter_zoned_date_time_range,
  filter_instant_equals,
  filter_instant_not_equal,
  filter_instant_greater_than,
  filter_instant_greater_than_or_equal,
  filter_instant_less_than,
  filter_instant_less_than_or_equal,
  filter_instant_range,
  filter_plain_date_time_equals,
  filter_plain_date_time_not_equal,
  filter_plain_date_time_greater_than,
  filter_plain_date_time_greater_than_or_equal,
  filter_plain_date_time_less_than,
  filter_plain_date_time_less_than_or_equal,
  filter_plain_date_time_range,
  filter_plain_date_equals,
  filter_plain_date_not_equal,
  filter_plain_date_greater_than,
  filter_plain_date_greater_than_or_equal,
  filter_plain_date_less_than,
  filter_plain_date_less_than_or_equal,
  filter_plain_date_range,
  filter_plain_time_equals,
  filter_plain_time_not_equal,
  filter_plain_time_greater_than,
  filter_plain_time_greater_than_or_equal,
  filter_plain_time_less_than,
  filter_plain_time_less_than_or_equal,
  filter_plain_time_range,
} from '#src/common/components/data-table/lib/filter-fns';
import {
  sort_zoned_date_time,
  sort_instant,
  sort_plain_date_time,
  sort_plain_date,
  sort_plain_time,
} from '#src/common/components/data-table/lib/sort-fns';

// v9's `tableFeatures({...})` is an explicit opt-in registry (unlike v8's
// single `useReactTable(options)` hook, where every feature was always
// present) — only sorting, column visibility/sizing/resizing, column +
// global filtering, and row selection are registered here since those are
// the only features this library builds support for so far (milestones
// 1-4 of the integration plan). Grouping/aggregation/pagination/pinning
// etc. are deliberately not registered — consumers needing them should
// extend this factory rather than expect it silently supports them.
export const dataTableFeatures = tableFeatures({
  // tableMeta: metaHelper<>(),
  columnMeta: metaHelper<DataTableColumnMeta>(),
  // filterMeta: metaHelper<>(),

  cellSelectionFeature,
  cellSpanningFeature,

  columnFacetingFeature,
  columnFilteringFeature,
  columnGroupingFeature,
  columnOrderingFeature,
  columnPinningFeature,
  columnResizingFeature,
  columnSizingFeature,
  columnVisibilityFeature,

  globalFilteringFeature,

  rowAggregationFeature,
  rowExpandingFeature,
  rowPaginationFeature,
  rowPinningFeature,
  rowSelectionFeature,
  rowSortingFeature,

  sortedRowModel: createSortedRowModel(),
  filteredRowModel: createFilteredRowModel(),
  expandedRowModel: createExpandedRowModel(),
  sortFns: {
    alphanumeric: sortFn_alphanumeric,
    alphanumericCaseSensitive: sortFn_alphanumericCaseSensitive,
    basic: sortFn_basic,
    datetime: sortFn_datetime,
    text: sortFn_text,
    textCaseSensitive: sortFn_textCaseSensitive,
    sort_zoned_date_time: sort_zoned_date_time,
    sort_instant: sort_instant,
    sort_plain_date_time: sort_plain_date_time,
    sort_plain_date: sort_plain_date,
    sort_plain_time: sort_plain_time,
  },
  filterFns: {
    arrIncludes: filterFn_arrIncludes,
    arrIncludesAll: filterFn_arrIncludesAll,
    arrHas: filterFn_arrHas,
    arrIncludesSome: filterFn_arrIncludesSome,
    between: filterFn_between,
    betweenInclusive: filterFn_betweenInclusive,
    empty: filterFn_empty,
    endsWith: filterFn_endsWith,
    equals: filterFn_equals,
    equalsString: filterFn_equalsString,
    equalsStringSensitive: filterFn_equalsStringSensitive,
    inDateRange: filterFn_inDateRange,
    inNumberRange: filterFn_inNumberRange,
    includesString: filterFn_includesString,
    includesStringSensitive: filterFn_includesStringSensitive,
    notEmpty: filterFn_notEmpty,
    startsWith: filterFn_startsWith,
    weakEquals: filterFn_weakEquals,
    filter_zoned_date_time_equals: filter_zoned_date_time_equals,
    filter_zoned_date_time_not_equal: filter_zoned_date_time_not_equal,
    filter_zoned_date_time_greater_than: filter_zoned_date_time_greater_than,
    filter_zoned_date_time_greater_than_or_equal: filter_zoned_date_time_greater_than_or_equal,
    filter_zoned_date_time_less_than: filter_zoned_date_time_less_than,
    filter_zoned_date_time_less_than_or_equal: filter_zoned_date_time_less_than_or_equal,
    filter_zoned_date_time_range: filter_zoned_date_time_range,
    filter_instant_equals: filter_instant_equals,
    filter_instant_not_equal: filter_instant_not_equal,
    filter_instant_greater_than: filter_instant_greater_than,
    filter_instant_greater_than_or_equal: filter_instant_greater_than_or_equal,
    filter_instant_less_than: filter_instant_less_than,
    filter_instant_less_than_or_equal: filter_instant_less_than_or_equal,
    filter_instant_range: filter_instant_range,
    filter_plain_date_time_equals: filter_plain_date_time_equals,
    filter_plain_date_time_not_equal: filter_plain_date_time_not_equal,
    filter_plain_date_time_greater_than: filter_plain_date_time_greater_than,
    filter_plain_date_time_greater_than_or_equal: filter_plain_date_time_greater_than_or_equal,
    filter_plain_date_time_less_than: filter_plain_date_time_less_than,
    filter_plain_date_time_less_than_or_equal: filter_plain_date_time_less_than_or_equal,
    filter_plain_date_time_range: filter_plain_date_time_range,
    filter_plain_date_equals: filter_plain_date_equals,
    filter_plain_date_not_equal: filter_plain_date_not_equal,
    filter_plain_date_greater_than: filter_plain_date_greater_than,
    filter_plain_date_greater_than_or_equal: filter_plain_date_greater_than_or_equal,
    filter_plain_date_less_than: filter_plain_date_less_than,
    filter_plain_date_less_than_or_equal: filter_plain_date_less_than_or_equal,
    filter_plain_date_range: filter_plain_date_range,
    filter_plain_time_equals: filter_plain_time_equals,
    filter_plain_time_not_equal: filter_plain_time_not_equal,
    filter_plain_time_greater_than: filter_plain_time_greater_than,
    filter_plain_time_greater_than_or_equal: filter_plain_time_greater_than_or_equal,
    filter_plain_time_less_than: filter_plain_time_less_than,
    filter_plain_time_less_than_or_equal: filter_plain_time_less_than_or_equal,
    filter_plain_time_range: filter_plain_time_range,
  },
  aggregationFns: {
    aggregationFn_sum: aggregationFn_sum,
    aggregationFn_min: aggregationFn_min,
    aggregationFn_max: aggregationFn_max,
    aggregationFn_extent: aggregationFn_extent,
    aggregationFn_mean: aggregationFn_mean,
    aggregationFn_median: aggregationFn_median,
    aggregationFn_unique: aggregationFn_unique,
    aggregationFn_uniqueCount: aggregationFn_uniqueCount,
    aggregationFn_first: aggregationFn_first,
    aggregationFn_last: aggregationFn_last,
    aggregation_zoned_date_time_min: aggregation_zoned_date_time_min,
    aggregation_zoned_date_time_max: aggregation_zoned_date_time_max,
    aggregation_zoned_date_time_extent: aggregation_zoned_date_time_extent,
    aggregation_instant_min: aggregation_instant_min,
    aggregation_instant_max: aggregation_instant_max,
    aggregation_instant_extent: aggregation_instant_extent,
    aggregation_plain_date_time_min: aggregation_plain_date_time_min,
    aggregation_plain_date_time_max: aggregation_plain_date_time_max,
    aggregation_plain_date_time_extent: aggregation_plain_date_time_extent,
    aggregation_plain_date_min: aggregation_plain_date_min,
    aggregation_plain_date_max: aggregation_plain_date_max,
    aggregation_plain_date_extent: aggregation_plain_date_extent,
    aggregation_plain_time_min: aggregation_plain_time_min,
    aggregation_plain_time_max: aggregation_plain_time_max,
    aggregation_plain_time_extent: aggregation_plain_time_extent,
  },
});

export type DataTableFeatures = typeof dataTableFeatures;

export const createFeaturedColumnHelper = <TData extends RowData>() => {
  return createColumnHelper<DataTableFeatures, TData>();
};
