import {
  createFilteredRowModel,
  createSortedRowModel,
  createExpandedRowModel,
  metaHelper,
  cellSelectionFeature,
  cellSpanningFeature,
  columnFacetingFeature,
  columnFilteringFeature,
  columnGroupingFeature,
  columnOrderingFeature,
  columnPinningFeature,
  columnResizingFeature,
  columnSizingFeature,
  columnVisibilityFeature,
  globalFilteringFeature,
  rowAggregationFeature,
  rowExpandingFeature,
  rowPaginationFeature,
  rowPinningFeature,
  rowSelectionFeature,
  rowSortingFeature,
  sortFn_alphanumeric,
  sortFn_datetime,
  sortFn_text,
  tableFeatures,
} from '@tanstack/react-table';

import type { DataTableColumnMeta } from '#src/common/components/data-table/lib/filter-fns';
import {
  filter_zoned_date_time_equals,
  filter_zoned_date_time_not_equal,
  filter_zoned_date_time_greater_than,
  filter_zoned_date_time_greater_than_or_equal,
  filter_zoned_date_time_less_than,
  filter_zoned_date_time_less_than_or_equal,
  filter_zoned_date_time_range,
  filter_instant_equals,
  filter_instant_not_equal,
  filter_instant_greater_than,
  filter_instant_greater_than_or_equal,
  filter_instant_less_than,
  filter_instant_less_than_or_equal,
  filter_instant_range,
  filter_plain_date_time_equals,
  filter_plain_date_time_not_equal,
  filter_plain_date_time_greater_than,
  filter_plain_date_time_greater_than_or_equal,
  filter_plain_date_time_less_than,
  filter_plain_date_time_less_than_or_equal,
  filter_plain_date_time_range,
  filter_plain_date_equals,
  filter_plain_date_not_equal,
  filter_plain_date_greater_than,
  filter_plain_date_greater_than_or_equal,
  filter_plain_date_less_than,
  filter_plain_date_less_than_or_equal,
  filter_plain_date_range,
  filter_plain_time_equals,
  filter_plain_time_not_equal,
  filter_plain_time_greater_than,
  filter_plain_time_greater_than_or_equal,
  filter_plain_time_less_than,
  filter_plain_time_less_than_or_equal,
  filter_plain_time_range,
} from '#src/common/components/data-table/lib/filter-fns';
import {
  sort_zoned_date_time,
  sort_instant,
  sort_plain_date_time,
  sort_plain_date,
  sort_plain_time,
} from '#src/common/components/data-table/lib/sort-fns';

// v9's `tableFeatures({...})` is an explicit opt-in registry (unlike v8's
// single `useReactTable(options)` hook, where every feature was always
// present) — only sorting, column visibility/sizing/resizing, column +
// global filtering, and row selection are registered here since those are
// the only features this library builds support for so far (milestones
// 1-4 of the integration plan). Grouping/aggregation/pagination/pinning
// etc. are deliberately not registered — consumers needing them should
// extend this factory rather than expect it silently supports them.
export const dataTableFeatures = tableFeatures({
  cellSelectionFeature,
  cellSpanningFeature,
  columnFacetingFeature,
  columnFilteringFeature,
  columnGroupingFeature,
  columnOrderingFeature,
  columnPinningFeature,
  columnResizingFeature,
  columnSizingFeature,
  columnVisibilityFeature,
  globalFilteringFeature,
  rowAggregationFeature,
  rowExpandingFeature,
  rowPaginationFeature,
  rowPinningFeature,
  rowSelectionFeature,
  rowSortingFeature,

  sortedRowModel: createSortedRowModel(),
  filteredRowModel: createFilteredRowModel(),
  expandedRowModel: createExpandedRowModel(),
  sortFns: {
    alphanumeric: sortFn_alphanumeric,
    datetime: sortFn_datetime,
    text: sortFn_text,
    sort_zoned_date_time: sort_zoned_date_time,
    sort_instant: sort_instant,
    sort_plain_date_time: sort_plain_date_time,
    sort_plain_date: sort_plain_date,
    sort_plain_time: sort_plain_time,
  },
  filterFns: {
    filter_zoned_date_time_equals: filter_zoned_date_time_equals,
    filter_zoned_date_time_not_equal: filter_zoned_date_time_not_equal,
    filter_zoned_date_time_greater_than: filter_zoned_date_time_greater_than,
    filter_zoned_date_time_greater_than_or_equal: filter_zoned_date_time_greater_than_or_equal,
    filter_zoned_date_time_less_than: filter_zoned_date_time_less_than,
    filter_zoned_date_time_less_than_or_equal: filter_zoned_date_time_less_than_or_equal,
    filter_zoned_date_time_range: filter_zoned_date_time_range,
    filter_instant_equals: filter_instant_equals,
    filter_instant_not_equal: filter_instant_not_equal,
    filter_instant_greater_than: filter_instant_greater_than,
    filter_instant_greater_than_or_equal: filter_instant_greater_than_or_equal,
    filter_instant_less_than: filter_instant_less_than,
    filter_instant_less_than_or_equal: filter_instant_less_than_or_equal,
    filter_instant_range: filter_instant_range,
    filter_plain_date_time_equals: filter_plain_date_time_equals,
    filter_plain_date_time_not_equal: filter_plain_date_time_not_equal,
    filter_plain_date_time_greater_than: filter_plain_date_time_greater_than,
    filter_plain_date_time_greater_than_or_equal: filter_plain_date_time_greater_than_or_equal,
    filter_plain_date_time_less_than: filter_plain_date_time_less_than,
    filter_plain_date_time_less_than_or_equal: filter_plain_date_time_less_than_or_equal,
    filter_plain_date_time_range: filter_plain_date_time_range,
    filter_plain_date_equals: filter_plain_date_equals,
    filter_plain_date_not_equal: filter_plain_date_not_equal,
    filter_plain_date_greater_than: filter_plain_date_greater_than,
    filter_plain_date_greater_than_or_equal: filter_plain_date_greater_than_or_equal,
    filter_plain_date_less_than: filter_plain_date_less_than,
    filter_plain_date_less_than_or_equal: filter_plain_date_less_than_or_equal,
    filter_plain_date_range: filter_plain_date_range,
    filter_plain_time_equals: filter_plain_time_equals,
    filter_plain_time_not_equal: filter_plain_time_not_equal,
    filter_plain_time_greater_than: filter_plain_time_greater_than,
    filter_plain_time_greater_than_or_equal: filter_plain_time_greater_than_or_equal,
    filter_plain_time_less_than: filter_plain_time_less_than,
    filter_plain_time_less_than_or_equal: filter_plain_time_less_than_or_equal,
    filter_plain_time_range: filter_plain_time_range,
  },
  columnMeta: metaHelper<DataTableColumnMeta>(),
});

export type DataTableFeatures = typeof dataTableFeatures;
