/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSplatRouteImport } from './routes/posts/$'
import { Route as DocsComponentsRouteRouteImport } from './routes/_docs/components/route'
import { Route as DocsComponentsComponentIDRouteImport } from './routes/_docs/components/$componentID'

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSplatRoute = PostsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DocsComponentsRouteRoute = DocsComponentsRouteRouteImport.update({
  id: '/_docs/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsComponentIDRoute =
  DocsComponentsComponentIDRouteImport.update({
    id: '/$componentID',
    path: '/$componentID',
    getParentRoute: () => DocsComponentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/components': typeof DocsComponentsRouteRouteWithChildren
  '/posts/$': typeof PostsSplatRoute
  '/components/$componentID': typeof DocsComponentsComponentIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/components': typeof DocsComponentsRouteRouteWithChildren
  '/posts/$': typeof PostsSplatRoute
  '/components/$componentID': typeof DocsComponentsComponentIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_docs/components': typeof DocsComponentsRouteRouteWithChildren
  '/posts/$': typeof PostsSplatRoute
  '/_docs/components/$componentID': typeof DocsComponentsComponentIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/posts' | '/components' | '/posts/$' | '/components/$componentID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts' | '/components' | '/posts/$' | '/components/$componentID'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_docs/components'
    | '/posts/$'
    | '/_docs/components/$componentID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  DocsComponentsRouteRoute: typeof DocsComponentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_docs/components': {
      id: '/_docs/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DocsComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/components/$componentID': {
      id: '/_docs/components/$componentID'
      path: '/$componentID'
      fullPath: '/components/$componentID'
      preLoaderRoute: typeof DocsComponentsComponentIDRouteImport
      parentRoute: typeof DocsComponentsRouteRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsSplatRoute: typeof PostsSplatRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsSplatRoute: PostsSplatRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface DocsComponentsRouteRouteChildren {
  DocsComponentsComponentIDRoute: typeof DocsComponentsComponentIDRoute
}

const DocsComponentsRouteRouteChildren: DocsComponentsRouteRouteChildren = {
  DocsComponentsComponentIDRoute: DocsComponentsComponentIDRoute,
}

const DocsComponentsRouteRouteWithChildren =
  DocsComponentsRouteRoute._addFileChildren(DocsComponentsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  DocsComponentsRouteRoute: DocsComponentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './configs/tanstack-router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
