/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as DocsRouteRouteImport } from './routes/_docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIDRouteImport } from './routes/posts/$postID'
import { Route as DocsColorsRouteImport } from './routes/_docs/colors'
import { Route as DocsComponentsRouteRouteImport } from './routes/_docs/components/route'
import { Route as DocsComponentsIndexRouteImport } from './routes/_docs/components/index'
import { Route as DocsComponentsComponentIDRouteImport } from './routes/_docs/components/$componentID'

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIDRoute = PostsPostIDRouteImport.update({
  id: '/$postID',
  path: '/$postID',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DocsColorsRoute = DocsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsRouteRoute = DocsComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsComponentsRouteRoute,
} as any)
const DocsComponentsComponentIDRoute =
  DocsComponentsComponentIDRouteImport.update({
    id: '/$componentID',
    path: '/$componentID',
    getParentRoute: () => DocsComponentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/components': typeof DocsComponentsRouteRouteWithChildren
  '/colors': typeof DocsColorsRoute
  '/posts/$postID': typeof PostsPostIDRoute
  '/components/$componentID': typeof DocsComponentsComponentIDRoute
  '/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/colors': typeof DocsColorsRoute
  '/posts/$postID': typeof PostsPostIDRoute
  '/components/$componentID': typeof DocsComponentsComponentIDRoute
  '/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/_docs/components': typeof DocsComponentsRouteRouteWithChildren
  '/_docs/colors': typeof DocsColorsRoute
  '/posts/$postID': typeof PostsPostIDRoute
  '/_docs/components/$componentID': typeof DocsComponentsComponentIDRoute
  '/_docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/components'
    | '/colors'
    | '/posts/$postID'
    | '/components/$componentID'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts'
    | '/colors'
    | '/posts/$postID'
    | '/components/$componentID'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/posts'
    | '/_docs/components'
    | '/_docs/colors'
    | '/posts/$postID'
    | '/_docs/components/$componentID'
    | '/_docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postID': {
      id: '/posts/$postID'
      path: '/$postID'
      fullPath: '/posts/$postID'
      preLoaderRoute: typeof PostsPostIDRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_docs/colors': {
      id: '/_docs/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof DocsColorsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/components': {
      id: '/_docs/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DocsComponentsRouteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/components/': {
      id: '/_docs/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsComponentsRouteRoute
    }
    '/_docs/components/$componentID': {
      id: '/_docs/components/$componentID'
      path: '/$componentID'
      fullPath: '/components/$componentID'
      preLoaderRoute: typeof DocsComponentsComponentIDRouteImport
      parentRoute: typeof DocsComponentsRouteRoute
    }
  }
}

interface DocsComponentsRouteRouteChildren {
  DocsComponentsComponentIDRoute: typeof DocsComponentsComponentIDRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsComponentsRouteRouteChildren: DocsComponentsRouteRouteChildren = {
  DocsComponentsComponentIDRoute: DocsComponentsComponentIDRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsComponentsRouteRouteWithChildren =
  DocsComponentsRouteRoute._addFileChildren(DocsComponentsRouteRouteChildren)

interface DocsRouteRouteChildren {
  DocsComponentsRouteRoute: typeof DocsComponentsRouteRouteWithChildren
  DocsColorsRoute: typeof DocsColorsRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsComponentsRouteRoute: DocsComponentsRouteRouteWithChildren,
  DocsColorsRoute: DocsColorsRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIDRoute: typeof PostsPostIDRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIDRoute: PostsPostIDRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './configs/tanstack-router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
